name: Build the latest version
on:
  push:
    paths:
      - "**.sh"
jobs:
  build:
    name: Build on ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the directory
        uses: actions/checkout@v2
      - name: Install squid proxy server
        run: sudo ./squid-proxyy-manager.sh --install
      - name: View the resolv.conf
        run: sudo cat /etc/resolv.conf
      - name: Test the local network.
        run: |
          curl -I https://www.example.com
          curl -I https://www.example.net
          curl -I https://www.example.org
