name: Build the latest version
on:
  push:
    paths:
      - "**.sh"
jobs:
  build:
    name: Build on ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the directory
        uses: actions/checkout@v2
      - name: Install squid proxy server
        run: sudo ./squid-proxy-manager.sh --install
      - name: Stop squid proxy server
        run: sudo ./squid-proxy-manager.sh --stop
      - name: Start squid proxy server
        run: sudo ./squid-proxy-manager.sh --start
      - name: Restart squid service
        run: sudo ./squid-proxy-manager.sh --restart
      - name: Add a new squid proxy user
        run: echo -e "\n" | sudo ./squid-proxy-manager.sh --add
      - name: Show the list of all squid users.
        run: sudo ./squid-proxy-manager.sh --list
      - name: Test squid proxy ddns.
        run: sudo ./squid-proxy-manager.sh --ddns
      - name: Test squid proxy backup.
        run: sudo ./squid-proxy-manager.sh --backup
      - name: Test squid proxy purge.
        run: sudo ./squid-proxy-manager.sh --purge
      - name: View the squid.conf
        run: sudo cat /etc/squid/squid.conf
      - name: View the blocked-domains.acl
        run: sudo cat /etc/squid/blocked-domains.acl
      - name: View the squid users file.
        run: sudo cat /etc/squid/users
      - name: View the resolv.conf
        run: sudo cat /etc/resolv.conf
      - name: Test the local network.
        run: |
          curl -I https://www.example.com
          curl -I https://www.example.net
          curl -I https://www.example.org
